app/urls.py
from django.urls import path
from .views import *
from app import views

app_name = 'home'


urlpatterns = [
        path('', views.loginFunction,name='login'),
        path('reg/', views.Reg,name='reg'),
        path('productlist/', views.Productlist,name='productlist'),
        path('logout/',logoutView,name='logout'),
        path('addproduct/',addproduct,name='addproduct'),
        path('save_product/',Saveproduct,name='save_product'),
        path('editproduct/<str:id>',Editproduct,name='editproduct'),
        path('deleteproduct/<str:id>',DeleteProduct,name='deleteproduct'),
        path('addproductcatogery/',views.addproductcatogery,name="addproductcatogery"),
        path('Save_Category/',views.SaveCategory,name="Save_Category"),
        path('editcategory/<str:id>',Editcategory,name='editcategory'),
        path('categorylist/', views.categorylist,name='categorylist'),
        path('deletecategory/<str:id>',DeleteCategory,name='deletecategory'),
        



]

myweb/urls.py
from django.contrib import admin
from django.urls import path,include
from myweb import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls', namespace='home')),
    path('web/',include('userapp.urls'))
]
urlpatterns += staticfiles_urlpatterns()

app/templates/addcategory.html
{% extends 'base.html' %} {% load static %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- JavaScript Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
  body {
    /* background-image: url({% static 'img/reg_bg.jpg' %}); */

    /* background-repeat: no-repeat; */
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

{% block content %}

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Add product category</h2>

              <form method="post" action="{% url 'home:Save_Category' %}">
                {% csrf_token %}

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example1cg">Name</label>
                  <input
                    type="text"
                    name="name"
                    id="form3Example1cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3cg"
                    >Category</label
                  >
                  <input
                    type="text"
                    id="category"
                    name="category"
                    class="form-control form-control-lg"
                  />
                </div>

                <div class="d-flex justify-content-center">
                  <button
                    type="submit"
                    class="btn btn-success btn-block btn-lg"
                  >
                    Add
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock%}

app/templates/addproduct.html
{% extends 'base.html' %} {% load static %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- JavaScript Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
  body {
    /* background-image: url({% static 'img/reg_bg.jpg' %}); */

    /* background-repeat: no-repeat; */
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

{% block content %}

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Add product</h2>

              <form method="post" action="{% url 'home:save_product' %}">
                {% csrf_token %}
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example1cg">Name</label>
                  <input
                    type="text"
                    name="name"
                    id="form3Example1cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3cg"
                    >Category</label
                  >
                  <!-- <input
                    type="text"
                    id="form3Example3cg"
                    name="starpcolor"
                    class="form-control form-control-lg"
                  /> -->
                  <select name="category" class="filter-selectbox">
                    {% for post in product %}
                        <option value="{{ post.id }}">{{ post.category }}</option>
                    {% endfor %} </select>
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example1cg"
                    >highlights</label
                  >
                  <input
                    type="text"
                    name="highlights"
                    id="form3Example1cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3cg">Price</label>
                  <input
                    type="number"
                    id="form3Example3cg"
                    name="price"
                    class="form-control form-control-lg"
                  />
                </div>

                <div class="d-flex justify-content-center">
                  <button
                    type="submit"
                    class="btn btn-success btn-block btn-lg"
                  >
                    Add
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock%}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% comment %} bootstrap design {% endcomment %}
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    />

    <style>
      body {
        font-family: "Lato", sans-serif;
        background-color: #f6f7f7 !important;
      }

      .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        /* background-color: #23384E; */
        background-color: #19242d;
        overflow-x: hidden;
        padding-top: 20px;
        /* border-radius: 2%; */
      }
      h2 {
        color: black;
      }

      .sidenav a {
        padding: 6px 6px 6px 50px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
      }

      .sidenav a:hover {
        /* color: #f1f1f1; */
        background-color: #134f5e;
        color: #079eb7;
        text-decoration: none;
      }

      #base_h1 {
        font-family: Georgia, sans-serif;
        font-size: 4.5em;
        letter-spacing: -2px;
        color: black;
        margin-left: 0%;
        margin-top: -10%;
        margin-bottom: 18%;
        background-color: white;
        /* border-radius: 0% 0% 10% 10%; */
        border-radius: 0% 0% 15% 7%;
        text-align: center;
      }
      #admin_head {
        font-family: "Trebuchet MS", sans-serif;
        font-size: 3em;
        letter-spacing: -2px;
        border-bottom: 2px solid black;
        text-transform: uppercase;
      }

      /* mobile view */

      /* @media screen and (max-width: 700px) {
    .sidenav {
      width: 100%;
      height: auto;
      position: relative;

    }
    #base_h1{
        text-align: center;
    }
    .sidenav a {float: left;}
    div.content {margin-left: 0;}
  }
  
  @media screen and (max-width: 600px) {
    .sidenav a {
      text-align: center;
      float: none;
    }
  } */
    </style>

    {% comment %} top navbar {% endcomment %}

    <style>


      #navbar {
        overflow: hidden;
        background-color: #19242D;
      }


      #navbar a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
      }

      #navbar a:hover {
        background-color: #ddd;
        color: black;
      }

      #navbar a.active {
        background-color: #079EB7;
        color: white;
      }
      .topnav-right {
        float: right;
      }

      .content {
        padding: 16px;
      }

      .sticky {
        {% comment %} position: fixed; {% endcomment %}
        position: sticky;
        top: 0;
        width: 100%;
      }

      .sticky + .content {
        padding-top: 60px;
      }
    </style>
  </head>

  <body>
    <div id="navbar">
      <div class="topnav-right">
        <a href="{% url 'home:logout' %}">logout</a>
      </div>
    </div>

    <div class="main">{% block content %} {% endblock %}</div>

    <script>
      window.onscroll = function () {
        myFunction();
      };

      var navbar = document.getElementById("navbar");
      var sticky = navbar.offsetTop;

      function myFunction() {
        if (window.pageYOffset >= sticky) {
          navbar.classList.add("sticky");
        } else {
          navbar.classList.remove("sticky");
        }
      }
    </script>
  </body>
</html>

app/templates/category_edit.html
{% extends 'base.html' %} {% load static %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- JavaScript Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<style>
  body {
    /* background-image: url({% static 'img/reg_bg.jpg' %}); */

    /* background-repeat: no-repeat; */
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

{% block content %}

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Update Profile</h2>

              <form method="post" action="">
                {% csrf_token %}

                <div class="form-outline mb-4">
                  <label class="form-label" for="email">Name</label>
                  <input
                    type="text"
                    name="name"
                    value="{{product.name}}"
                    class="form-control form-control-lg"
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example4cg"
                    >Category</label
                  >
                  <input
                    type="text"
                    value="{{product.category}}"
                    name="category"
                    id="category"
                    class="form-control form-control-lg"
                  />
                </div>

                <div class="d-flex justify-content-center">
                  <button
                    type="submit"
                    id="submitButton"
                    class="btn btn-success btn-block btn-lg"
                  >
                    Update
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"
></script>

{% endblock%}

app/templates/login.html
{% load static %}

<style>
    #login_head{
        font-family:"Playfair Display", serif; font-weight:400;
  font-weight: 300;
  font-size: 38px;
  color: black;
  -webkit-transition: all 0.4s ease 0s;
  -o-transition: all 0.4s ease 0s;
  transition: all 0.4s ease 0s;
  margin-left: 8%;
margin-top: 10%;

    }
</style>
{% comment %} bootstrap design {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<link rel="stylesheet" href="{% static 'css/all_login.css' %}">


<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <!-- <h1>CRS</h1> -->
                <h1 id="login_head"></h1><br>

            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                   
                    <div class="img" style="background-image: url({% static 'img/login_bg.jpg' %})">
              </div>
                    <div class="login-wrap p-4 p-md-5">
                  <div class="d-flex">
                      <div class="w-100">
                          <h3 class="mb-4">Sign In</h3>
                      </div>
                    
                  </div>
                        <form action="#" method="post" class="signin-form">
                            {% csrf_token %}
                      <div class="form-group mb-3">
                          <label class="label" for="name">Email</label>
                          <input type="email" name="username" class="form-control" placeholder="Email" required>
                      </div>
                <div class="form-group mb-3">
                    <label class="label" for="password">Password</label>
                  <input type="password" name="password" class="form-control" placeholder="Password" required>
                </div>
                {% if messages %}
                           <div class="col-lg-12 color03 ">
                              {% for message in messages %}
                              <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                           </div>
                           {% endfor %}
                     </div>
                 {% endif %}
                <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary rounded submit px-3">Sign In</button>
                </div>
               
              </form>
              <p class="text-center">Not a member? <a data-toggle="tab" href="{% url 'home:reg' %}">Sign Up</a></p>

            </div>
          </div>
            </div>
        </div>
    </div>
</section>
</section>

app/templates/product_category.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style>
  #admin_head{
    font-family: "Trebuchet MS", sans-serif;
    font-size: 3em;
    letter-spacing: -2px;
    border-bottom: 2px solid black;
    text-transform: uppercase;
  }
  div.dataTables_wrapper div.dataTables_length select {
    width: 65px;
    display: inline-block;
    height: 0%;
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.js"
></script>

<link href="assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="assets/css/style.css" rel="stylesheet" />
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.css"
/>

<button onclick="window.location.href='{% url 'home:addproductcatogery' %}'" class="nav-item nav-link px-3 btn-blue">
  Add Product Category
</button>

<button onclick="window.location.href='{% url 'home:addproduct' %}'" class="nav-item nav-link px-3 btn-green">
  Add Product
</button>
<button onclick="window.location.href='{% url 'home:addproduct' %}'" class="nav-item nav-link px-3 btn-green">
  Add Enquiry Details
</button>

<h1 id="admin_head">Products</h1>

<table class="table table-striped" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for i in product %}
    <tr>
      <td scope="row">{{forloop.counter}}</td>
      <td>{{i.name}}</td>
      <td>{{i.category}}</td>
      <td>
        <a
          href="{% url 'home:editcategory' i.id %}"
          class="nav-item nav-link px-3"
          >Edit</a
        >
      </td>
      <td>
        <a
          href="{% url 'home:deletecategory' i.id %}"
          class="nav-item nav-link px-3"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  $(document).ready(function () {
    $("#table_id").DataTable();
  });
</script>

{% endblock%}

app/templates/productlist.html
{% extends 'base.html' %} {% load static %} {% block content %}

<style>
  #admin_head{
    font-family: "Trebuchet MS", sans-serif;
    font-size: 3em;
    letter-spacing: -2px;
    border-bottom: 2px solid black;
    text-transform: uppercase;
  }
  div.dataTables_wrapper div.dataTables_length select {
    width: 65px;
    display: inline-block;
    height: 0%;
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.js"
></script>

<link href="assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="assets/css/style.css" rel="stylesheet" />
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/dt-1.10.13/b-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.css"
/>

<button onclick="window.location.href='{% url 'home:addproductcatogery' %}'" class="nav-item nav-link px-3 btn-blue">
  Add Product Category
</button>

<button onclick="window.location.href='{% url 'home:addproduct' %}'" class="nav-item nav-link px-3 btn-green">
  Add Product
</button>
<button onclick="window.location.href='{% url 'home:addproduct' %}'" class="nav-item nav-link px-3 btn-green">
  Add Enquiry Details
</button>



<h1 id="admin_head">Products</h1>

<table class="table table-striped" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">highlights</th>
      <th scope="col">price</th>
      <th scope="col">edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for i in product %}
    <tr>
      <td scope="row">{{forloop.counter}}</td>
      <td>{{i.name}}</td>
      <td>{{i.category}}</td>
      <td>{{i.highlights}}</td>
      <td>{{i.price}}</td>
      <td>
        <a
          href="{% url 'home:editproduct' i.product_id %}"
          class="nav-item nav-link px-3"
          >Edit</a
        >
      </td>
      <td>
        <a
          href="{% url 'home:deleteproduct' i.product_id %}"
          class="nav-item nav-link px-3"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  $(document).ready(function () {
    $("#table_id").DataTable();
  });
</script>

{% endblock%}

app/templates/register.html
{% load static %} {% comment %} bootstrap design {% endcomment %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
<!-- JavaScript Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
  crossorigin="anonymous"
></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
/>

<style>

  body{
      /* background-image: url({% static 'img/reg_bg.jpg' %}); */
      {% comment %} background-color: #FFBD54;  {% endcomment %}
      /* background-repeat: no-repeat; */
    background-size: 100% 100%;
    background-color: darkslategray;
  }
</style>

<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px; margin: 5%">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form method="post" action="">
                {% csrf_token %}
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example1cg"
                    >Your Name</label
                  >
                  <input
                    type="text"
                    autofocus
                    name="name"
                    id="form3Example1cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="email">Your Email</label>
                  <input
                    type="email"
                    name="email"
                    id="email"
                    class="form-control form-control-lg"
                    required
                  />
                  <div id="emailerror" style="color: red; display: none">
                    This email already being used!
                  </div>
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3cg"
                    >Your Phone number</label
                  >
                  <input
                    type="number"
                    name="phone"
                    id="form3Example3cg"
                    pattern="/^-?\d+\.?\d*$/"
                    onKeyPress="if(this.value.length==10) return false;"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example4cg"
                    >Address</label
                  >
                  <input
                    type="text"
                    name="address"
                    id="form3Example4cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example4cg">City</label>
                  <input
                    type="text"
                    name="city"
                    id="form3Example4cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example4cg"
                    >Pincode</label
                  >
                  <input
                    type="number"
                    name="pincode"
                    id="form3Example4cg"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="password" name="password"
                    >Password</label
                  >
                  <input
                    type="password"
                    id="password"
                    name="password"
                    class="form-control form-control-lg"
                    required
                  />
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="confirm_password"
                    >Confirm password</label
                  >
                  <input
                    type="password"
                    id="confirm_password"
                    class="form-control form-control-lg"
                    name="password"
                    required
                  />
                  <span id="message"></span>
                </div>

                <div class="d-flex justify-content-center">
                  <button
                    type="submit"
                    id="submitButton"
                    class="btn btn-success btn-block btn-lg"
                  >
                    Register
                  </button>
                </div>

                <p class="text-center text-muted mt-5 mb-0">
                  Have already an account?
                  <a href="{% url 'home:login' %}" class="fw-bold text-body"
                    ><u>Login here</u></a
                  >
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $("#confirm_password").on("keyup", function () {
    document.getElementById("submitButton").disabled = true;
    var pass_value = document.getElementById("password").value;
    if (pass_value == "") {
      document.getElementById("submitButton").disabled = true;
    } else {
      if ($("#password").val() == $("#confirm_password").val()) {
        $("#message").html("");
        document.getElementById("submitButton").disabled = false;
      } else $("#message").html("Passwords not matching!").css("color", "red");
    }
  });
</script>